### ISSUE TITLE
Turn off quote stripping in HTML minify

### ISSUE THREAD

**Issue by motatoes** [phonegap/phonegap-template-vue-f7-blank#12]
Related to [this issue](https://github.com/webpack-contrib/html-loader/issues/119), I was having problems testing my app in the phonegap app, since it did not refresh automatically. [The fix for me](https://github.com/phonegap/phonegap-app-developer/issues/287#issuecomment-241323885) was to have the `<script type="text/javascript" src="cordova.js"></script>` as the last script in the document (it is strange).

As a fix for this I had to:

- change `inject: true` to `inject: false` in both [`build\webpack-dev.conf.js`](https://github.com/phonegap/phonegap-template-vue-f7-blank/blob/master/template/build/webpack.dev.conf.js#L34) and [`build\webpack-prod.conf.js`](https://github.com/phonegap/phonegap-template-vue-f7-blank/blob/master/template/build/webpack.prod.conf.js#L48).
- Replace the script injection section in `src\index.html` with:

```
<% for (var chunk in htmlWebpackPlugin.files.chunks) { %>
<script type="text/javascript" src="<%= htmlWebpackPlugin.files.chunks[chunk].entry %>"></script>
<% } %>
<script type="text/javascript" src="cordova.js"></script>
```
I can submit a PR with these changes if required :)

**Comment by devgeeks** [comment]
Would turning off `removeAttributeQuotes` help?

https://github.com/phonegap/phonegap-template-vue-f7-blank/blob/master/template/build/webpack.prod.conf.js#L52

**Comment by motatoes** [comment]
Hi @devgeeks 

I can confirm that the following fixes the reload issue:

1- turning off `removeAttributeQuotes` as you stated and
2- Adding the [MIME type](https://github.com/phonegap/phonegap-app-developer/issues/287#issuecomment-241323885) to the [cordova script tag](https://github.com/phonegap/phonegap-template-vue-f7-blank/blob/master/template/src/index.html#L28) in `src/index.html`: 

    <script type="text/javascript" src="cordova.js"></script>

**Comment by devgeeks** [comment]
@motatoes OK. Thanks for working that out. I'll update all three templates with those fixes and publish to npm!

**Comment by devgeeks** [comment]
Published to NPM as well.

Thanks @motatoes
