### ISSUE TITLE
Wrong source path for static assets ?

### ISSUE THREAD

**Issue by motatoes** [phonegap/phonegap-template-vue-f7-blank#13]
Hello!

I think the [line](https://github.com/phonegap/phonegap-template-vue-f7-blank/blob/master/template/build/build.js#L22)

    cp('-R', 'static/*', assetsPath);

should change to

    cp('-R', 'src/static/*', assetsPath);

In order to copy the static folder from the src dir to the www dir. Is that what is intended?

**Comment by devgeeks** [comment]
There is also a `./static` folder. It doesn't have anything in it by default, but assets can be put there. 

The `./src/static` folder is dealt with elsewhere IIRC.

See: https://vuejs-templates.github.io/webpack/static.html
