### ISSUE TITLE
Any plans to upgrade to Framework7 v3?

### ISSUE THREAD

**Issue by florimm** [phonegap/phonegap-template-vue-f7-blank#30]
Any plans to upgrade to Framework7 v3?

**Comment by micromacrotechnology** [comment]
+1 for this

**Comment by timkim** [comment]
Working on one here: https://github.com/phonegap/phonegap-template-vue-f7-blank/tree/upgradeFramework7

**Comment by timkim** [comment]
All right, changes are in!
